### ISSUE TITLE
high cpu consumption from java file notification libary

### ISSUE THREAD

**Issue by eostermueller** [eostermueller/performanceAnalysisWorkbench#75]
![image](https://user-images.githubusercontent.com/175773/173244319-5519c1ee-42b5-4848-a537-b7a452b682f4.png)

![image](https://user-images.githubusercontent.com/175773/173244443-b3a634fa-3955-415a-91ec-b9e2f2706bee.png)

**Comment by eostermueller** [comment]
[thread-dumps.zip](https://github.com/eostermueller/performanceAnalysisWorkbench/files/8886312/thread-dumps.zip)

```
"main" #1 prio=5 os_prio=0 cpu=2231890.63ms elapsed=74353.14s tid=0x000001ee3d757000 nid=0xb50 runnable  [0x0000002720bfc000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.fs.WindowsNativeDispatcher.CreateFile0(java.base@11.0.5/Native Method)
        at sun.nio.fs.WindowsNativeDispatcher.CreateFile(java.base@11.0.5/WindowsNativeDispatcher.java:71)
        at sun.nio.fs.WindowsChannelFactory.open(java.base@11.0.5/WindowsChannelFactory.java:308)
        at sun.nio.fs.WindowsChannelFactory.newFileChannel(java.base@11.0.5/WindowsChannelFactory.java:168)
        at sun.nio.fs.WindowsFileSystemProvider.checkReadAccess(java.base@11.0.5/WindowsFileSystemProvider.java:330)
        at sun.nio.fs.WindowsFileSystemProvider.checkAccess(java.base@11.0.5/WindowsFileSystemProvider.java:367)
        at sun.nio.fs.AbstractFileSystemProvider.exists(java.base@11.0.5/AbstractFileSystemProvider.java:151)
        at java.nio.file.Files.exists(java.base@11.0.5/Files.java:2434)
        at com.github.eostermueller.perfgoat.BlockOnSentinelFile.block(BlockOnSentinelFile.java:74)
        at com.github.eostermueller.perfgoat.ITBlock.test(ITBlock.java:16)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@11.0.5/Native Method)

```

**Comment by eostermueller** [comment]
Looks like this has been highlighted before:
[https://bugs.openjdk.org/browse/JDK-8230055](https://bugs.openjdk.org/browse/JDK-8230055)
